title: Corazón tan rancio
email: corazontanrancio@gmail.com	
description: "Javier Marías para la gente con prisa."
baseurl: ""
url: "http://corazontanrancio.github.io"
twitter_username: corazontanrancio
github_username:  corazontanrancio

# Build settings
markdown: kramdown
permalink: pretty

paginate: 4

author: Your name

gems: [jekyll-paginate]
