# Site settings
title: Corazón tan rancio
email: corazontanrancio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Javier Marías para la gente con prisa.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://corazontanrancio.github.io # the base hostname & protocol for your site
github_username:  corazontanrancio

about: "No todo el mundo tuvo un padre filósofo o estudió en una institución pedagógica revolucionaria. Este blog intenta hacer más accesibles las columnas de opinión del escritor, traductor, editor y, por qué no decirlo, madurito interesante Javier Marías."

# Build settings
markdown: kramdown

paginate: 4

author: Manuel Jaurías

gems: [jekyll-paginate]
